version: "1"

services:

  app:
    image: teamplayerapp:latest

    container_name: teamplayerapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mydb
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: mydb-kiii
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=matea123
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
