apiVersion: v1
kind: Service
metadata:
  name: teamplayerapp-service
  namespace: teamplayerapp
spec:
  selector:
    app: teamplayerapp
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP