name: Build and Push Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Update to the latest version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Update to the latest version
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Update to the latest version
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/teamplayerapp:latest

      - name: Verify Docker image
        run: docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/teamplayerapp:latest
